-- Migration: create comprehensive analytics tables

CREATE TABLE IF NOT EXISTS visites (
  id INT AUTO_INCREMENT PRIMARY KEY,
  portfolio_id INT NOT NULL,
  adresse_ip VARCHAR(45) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  referer VARCHAR(500) DEFAULT NULL,
  page VARCHAR(500) NOT NULL,
  pays VARCHAR(2) DEFAULT NULL,
  ville VARCHAR(100) DEFAULT NULL,
  latitude DECIMAL(10, 8) DEFAULT NULL,
  longitude DECIMAL(11, 8) DEFAULT NULL,
  date_visite TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_new_session BOOLEAN DEFAULT TRUE,
  session_id VARCHAR(32) DEFAULT NULL,
  session_start TIMESTAMP NULL,
  session_end TIMESTAMP NULL,
  device_type ENUM('desktop', 'mobile', 'tablet', 'bot', 'other') DEFAULT NULL,
  browser VARCHAR(50) DEFAULT NULL,
  os VARCHAR(50) DEFAULT NULL,
  screen_width INT DEFAULT NULL,
  screen_height INT DEFAULT NULL,
  INDEX idx_portfolio (portfolio_id),
  INDEX idx_date (date_visite),
  INDEX idx_session (session_id),
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS analytics_events_2 (
  id INT AUTO_INCREMENT PRIMARY KEY,
  portfolio_id INT NOT NULL,
  session_id VARCHAR(32) DEFAULT NULL,
  type ENUM(
    'click',
    'scroll',
    'hover',
    'form_submit',
    'download',
    'video_play',
    'social_share',
    'project_view',
    'contact_click',
    'cv_download',
    'appointment_book',
    'external_link'
  ) NOT NULL,
  page VARCHAR(500) NOT NULL,
  element_id VARCHAR(100) DEFAULT NULL,
  element_class VARCHAR(200) DEFAULT NULL,
  element_text TEXT DEFAULT NULL,
  coordinates_x DECIMAL(5, 2) DEFAULT NULL,
  coordinates_y DECIMAL(5, 2) DEFAULT NULL,
  scroll_depth DECIMAL(5, 2) DEFAULT NULL COMMENT '0-100%',
  metadata JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_portfolio_type (portfolio_id, type),
  INDEX idx_session (session_id),
  INDEX idx_created (created_at),
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS projet_views (
  id INT AUTO_INCREMENT PRIMARY KEY,
  portfolio_id INT NOT NULL,
  projet_id INT NOT NULL,
  view_count INT DEFAULT 1,
  unique_views INT DEFAULT 1,
  total_time_ms BIGINT DEFAULT 0,
  last_viewed TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_portfolio_projet (portfolio_id, projet_id),
  INDEX idx_popularity (view_count DESC),
  UNIQUE KEY uniq_portfolio_projet (portfolio_id, projet_id),
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE,
  FOREIGN KEY (projet_id) REFERENCES projets(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS conversions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  portfolio_id INT NOT NULL,
  type ENUM('contact', 'cv', 'appointment', 'newsletter', 'demo_request') NOT NULL,
  contact_method ENUM('form', 'email', 'phone', 'whatsapp') DEFAULT NULL,
  contact_name VARCHAR(150) DEFAULT NULL,
  contact_email VARCHAR(150) DEFAULT NULL,
  contact_phone VARCHAR(20) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  source_page VARCHAR(500) NOT NULL,
  utm_source VARCHAR(100) DEFAULT NULL,
  utm_medium VARCHAR(100) DEFAULT NULL,
  utm_campaign VARCHAR(100) DEFAULT NULL,
  session_id VARCHAR(32) DEFAULT NULL,
  is_qualified BOOLEAN DEFAULT FALSE,
  qualification_score TINYINT DEFAULT 0 COMMENT '0-100',
  follow_up_status ENUM('new', 'contacted', 'responded', 'converted', 'lost') DEFAULT 'new',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_portfolio_type (portfolio_id, type),
  INDEX idx_date (created_at),
  INDEX idx_qualified (is_qualified),
  INDEX idx_session (session_id),
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS performance_metrics (
  id INT AUTO_INCREMENT PRIMARY KEY,
  portfolio_id INT NOT NULL,
  page_url VARCHAR(500) NOT NULL,
  load_time_ms INT DEFAULT NULL,
  first_contentful_paint_ms INT DEFAULT NULL,
  largest_contentful_paint_ms INT DEFAULT NULL,
  first_input_delay_ms INT DEFAULT NULL,
  cumulative_layout_shift DECIMAL(5, 3) DEFAULT NULL,
  time_to_interactive_ms INT DEFAULT NULL,
  dom_size INT DEFAULT NULL,
  total_blocking_time_ms INT DEFAULT NULL,
  device_type ENUM('desktop', 'mobile') DEFAULT 'desktop',
  connection_type VARCHAR(50) DEFAULT NULL,
  tested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_portfolio_page (portfolio_id, page_url),
  INDEX idx_tested (tested_at),
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS performance_scores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  portfolio_id INT NOT NULL,
  date DATE NOT NULL,
  overall_score TINYINT UNSIGNED DEFAULT 0,
  traffic_score TINYINT UNSIGNED DEFAULT 0,
  engagement_score TINYINT UNSIGNED DEFAULT 0,
  conversion_score TINYINT UNSIGNED DEFAULT 0,
  content_score TINYINT UNSIGNED DEFAULT 0,
  seo_score TINYINT UNSIGNED DEFAULT 0,
  technical_score TINYINT UNSIGNED DEFAULT 0,
  total_visits INT DEFAULT 0,
  unique_visitors INT DEFAULT 0,
  avg_session_duration_seconds INT DEFAULT 0,
  bounce_rate DECIMAL(5, 2) DEFAULT 0,
  conversion_rate DECIMAL(5, 2) DEFAULT 0,
  pages_per_session DECIMAL(5, 2) DEFAULT 0,
  trend_traffic DECIMAL(5, 2) DEFAULT 0 COMMENT '% change vs previous period',
  trend_engagement DECIMAL(5, 2) DEFAULT 0,
  trend_conversion DECIMAL(5, 2) DEFAULT 0,
  badges JSON DEFAULT NULL COMMENT 'List of badges earned {"name": "...", "earned_at": "..."}',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_portfolio_date (portfolio_id, date),
  INDEX idx_date (date),
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS traffic_sources (
  id INT AUTO_INCREMENT PRIMARY KEY,
  portfolio_id INT NOT NULL,
  date DATE NOT NULL,
  source_type ENUM(
    'organic_search',
    'paid_search',
    'direct',
    'referral',
    'social',
    'email',
    'other'
  ) NOT NULL,
  source_detail VARCHAR(200) DEFAULT NULL,
  medium VARCHAR(50) DEFAULT NULL,
  campaign VARCHAR(100) DEFAULT NULL,
  keyword VARCHAR(200) DEFAULT NULL,
  visits INT DEFAULT 0,
  unique_visitors INT DEFAULT 0,
  conversions INT DEFAULT 0,
  conversion_value DECIMAL(10, 2) DEFAULT 0,
  bounce_rate DECIMAL(5, 2) DEFAULT 0,
  avg_duration_seconds INT DEFAULT 0,
  INDEX idx_portfolio_date (portfolio_id, date),
  INDEX idx_source (source_type),
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_sessions (
  id VARCHAR(32) PRIMARY KEY,
  portfolio_id INT NOT NULL,
  adresse_ip VARCHAR(45) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  referer VARCHAR(500) DEFAULT NULL,
  landing_page VARCHAR(500) NOT NULL,
  device_type ENUM('desktop', 'mobile', 'tablet') DEFAULT NULL,
  country VARCHAR(2) DEFAULT NULL,
  start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  end_time TIMESTAMP NULL,
  duration_seconds INT DEFAULT 0,
  page_count INT DEFAULT 1,
  is_bounced BOOLEAN DEFAULT TRUE,
  has_converted BOOLEAN DEFAULT FALSE,
  conversion_type VARCHAR(50) DEFAULT NULL,
  exit_page VARCHAR(500) DEFAULT NULL,
  INDEX idx_portfolio_time (portfolio_id, start_time),
  INDEX idx_duration (duration_seconds),
  INDEX idx_converted (has_converted),
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS gamification_badges (
  id INT AUTO_INCREMENT PRIMARY KEY,
  portfolio_id INT NOT NULL,
  badge_key VARCHAR(50) NOT NULL,
  badge_name VARCHAR(100) NOT NULL,
  badge_description TEXT DEFAULT NULL,
  badge_type ENUM('bronze', 'silver', 'gold', 'platinum', 'legendary') DEFAULT 'bronze',
  category ENUM('traffic', 'engagement', 'conversion', 'seo', 'technical', 'achievement') NOT NULL,
  required_value DECIMAL(10, 2) DEFAULT NULL,
  current_value DECIMAL(10, 2) DEFAULT 0,
  progress_percentage TINYINT UNSIGNED DEFAULT 0,
  is_earned BOOLEAN DEFAULT FALSE,
  earned_at TIMESTAMP NULL,
  metadata JSON DEFAULT NULL,
  INDEX idx_portfolio (portfolio_id),
  INDEX idx_earned (is_earned),
  UNIQUE KEY uniq_portfolio_badge (portfolio_id, badge_key),
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ai_insights (
  id INT AUTO_INCREMENT PRIMARY KEY,
  portfolio_id INT NOT NULL,
  insight_type ENUM('tip', 'warning', 'success', 'opportunity', 'prediction') NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  confidence_score TINYINT UNSIGNED DEFAULT 0 COMMENT '0-100',
  related_metrics JSON DEFAULT NULL COMMENT '{"metric": "conversion_rate", "value": 4.5, "target": 5}',
  suggested_action TEXT DEFAULT NULL,
  action_url VARCHAR(500) DEFAULT NULL,
  is_applied BOOLEAN DEFAULT FALSE,
  applied_at TIMESTAMP NULL,
  impact_score TINYINT UNSIGNED DEFAULT NULL COMMENT 'Estimated impact 0-100',
  generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NULL,
  INDEX idx_portfolio_type (portfolio_id, insight_type),
  INDEX idx_generated (generated_at),
  INDEX idx_confidence (confidence_score DESC),
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
) ENGINE=InnoDB;
